name: On Merge

on:
  push:
    branches:
      - main
    paths:
      - 'speech.txt'

jobs:
  synthesize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run synthesis
        env:
          ACMELABS_SYNTHESIZE_AWS_S3_BUCKET: ${{ secrets.ACMELABS_SYNTHESIZE_AWS_S3_BUCKET }}
          ACMELABS_SYNTHESIZE_AWS_S3_PREFIX: ${{ vars.ACMELABS_SYNTHESIZE_AWS_S3_PREFIX }}
          ACMELABS_SYNTHESIZE_AWS_S3_KEY: ${{ vars.ACMELABS_SYNTHESIZE_AWS_S3_KEY_PROD }}
        run: |
          echo "S3_BUCKET: ${{ secrets.ACMELABS_SYNTHESIZE_AWS_S3_BUCKET }}"
          echo "S3_PREFIX: ${{ vars.ACMELABS_SYNTHESIZE_AWS_S3_PREFIX }}"
          echo "S3_KEY: ${{ vars.ACMELABS_SYNTHESIZE_AWS_S3_KEY_PROD }}"
          python synthesize.py

      - name: Upload to S3 (Prod)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACMELABS_SYNTHESIZE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACMELABS_SYNTHESIZE_AWS_SECRET_ACCESS_KEY }}
        run: |
          python synthesize.py
