name: On Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'speech.txt'

jobs:
  synthesize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run synthesis
        env:
          AcmeLabsSynthesize_AWS_S3_BUCKET: ${{ secrets.AcmeLabsSynthesize_AWS_S3_BUCKET }}
          AcmeLabsSynthesize_AWS_S3_PREFIX: ${{ vars.AcmeLabsSynthesize_AWS_S3_PREFIX }}
          AcmeLabsSynthesize_AWS_S3_KEY: ${{ vars.AcmeLabsSynthesize_AWS_S3_KEY_BETA }}
        run: |
          python synthesize.py

      - name: Upload to S3 (Beta)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AcmeLabsSynthesize_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AcmeLabsSynthesize_AWS_SECRET_ACCESS_KEY }}
        run: |
          python synthesize.py
